/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "DIO_interface.h"
#include "NVIC_interface.h"
#include "EXTI_interface.h"
#include "SYSCFG_interface.h"
#include "STK_interface.h"
#include "IR_interface.h"

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

int main(void)
{
	RCC_voidInitSystemClock();
	RCC_voidEnableClock(RCC_AHB1, 0);
	RCC_voidEnableClock(RCC_AHB1, 1);
	RCC_voidEnableClock(RCC_APB2, 14);

	MGPIO_PinType GPIO_Init = {.MODE = GENERAL_OUTPUT , .InputPullType=NONE , .OutputSpeed =LOW_SPEED ,
			.OutputType = PUSH_PULL};

	MGPIO_VidSetPinDirection(GPIOB, 3, &GPIO_Init);
	MGPIO_VidSetPinDirection(GPIOB, 4, &GPIO_Init);
	MGPIO_VidSetPinDirection(GPIOB, 5, &GPIO_Init);

	HIR_voidInit();
	Remote x=0;
	u8 RGB[3]={0};
	while(1)
	{
		x=HIR_u8GetKeyValue();
		if(x==69)
		{
			TOGGLE_BIT(RGB[0],0);
			MGPIO_VidSetPinValue(GPIOB, 3, RGB[0]);
		}
		else if (x==70)
		{
			TOGGLE_BIT(RGB[1],0);
			MGPIO_VidSetPinValue(GPIOB, 4, RGB[1]);
		}
		else if (x==71)
				{
					TOGGLE_BIT(RGB[2],0);
					MGPIO_VidSetPinValue(GPIOB, 5, RGB[2]);
				}

	}
}

